In [1]:
import sys
import numpy as np
caeUtilPath = 'D:/ewhalen/OneDrive - Massachusetts Institute of Technology/research/toolbox/caeSurrogateUtility/'
if caeUtilPath not in sys.path: sys.path.append(caeUtilPath)
import caeUtility as cu

In [2]:
trueFields = [np.array([0.1, 0.1, 0.3]), 
              np.array([0.1, 0.2, 0.5]),
              np.array([1.7, 0.2, 0.6])]

predictions = [np.array([0.0, 0.2, 0.2]), 
               np.array([0.0, 0.2, 0.9]),
               np.array([1.6, 0.1, 0.6])]

cu.computeFieldLossMetrics(trueFields, predictions, level='point')

{'errors': [array([-0.1,  0.1, -0.1]),
  array([-0.1,  0. ,  0.4]),
  array([-0.1, -0.1,  0. ])],
 'relErrs': [array([0.90909091, 0.47619048, 0.32258065]),
  array([0.90909091, 0.        , 0.43956044]),
  array([0.05847953, 0.47619048, 0.        ])]}

In [3]:
cu.computeFieldLossMetrics(trueFields, predictions, level='field')

{'mse': [0.01, 0.05666666666666668, 0.006666666666666658],
 'mae': [0.09999999999999999, 0.16666666666666666, 0.06666666666666662],
 'mre': [0.5692873434808919, 0.4495504495504496, 0.17822333611807292],
 'maxAE': [0.1, 0.4, 0.1],
 'mae/peak': [0.3333333333333333, 0.3333333333333333, 0.03921568627450978],
 'maxAE/peak': [0.33333333333333337, 0.8, 0.05882352941176471],
 'relEAtPeak': [0.33333333333333326, 0.8, 0.05882352941176463]}

In [4]:
cu.computeFieldLossMetrics(trueFields, predictions, level='set')

{'mse': 0.024444444444444446,
 'mae': 0.1111111111111111,
 'mre': 0.3990203763831381,
 'peakR2': 0.8430232558139534,
 'maxAggR2': 0.982421875,
 'meanAggR2': -1.2201450892857149,
 'minAggR2': -2.642857142857144}

In [5]:
cu.computeFieldLossMetrics(trueFields, predictions, level='set', baselineRef=trueFields)

{'mse': 0.024444444444444446,
 'mae': 0.1111111111111111,
 'mre': 0.3990203763831381,
 'mse/baseline': 0.125,
 'mae/baseline': 0.3846153846153846,
 'peakR2': 0.8430232558139534,
 'maxAggR2': 0.982421875,
 'meanAggR2': -1.2201450892857149,
 'minAggR2': -2.642857142857144}

In [6]:
cu.computeFieldLossMetrics(trueFields, predictions, level='point_agg')

{'mse': array([0.01      , 0.00666667, 0.05666667]),
 'mae': array([0.1       , 0.06666667, 0.16666667]),
 'mre': array([0.62555378, 0.31746032, 0.25404703]),
 'r2': array([ 0.98242188, -2.        , -2.64285714])}

In [7]:
cu.baseline(trueFields, trueFields, avgLevel='point', level='set')

{'mse': 0.19555555555555557,
 'mae': 0.2888888888888889,
 'mre': 0.4011356260299692,
 'peakR2': -0.10465116279069786,
 'maxAggR2': 0.0,
 'meanAggR2': 0.0,
 'minAggR2': 0.0}

In [8]:
cu.baseline(trueFields, trueFields, avgLevel='set', level='set')

{'mse': 0.2328395061728395,
 'mae': 0.34074074074074073,
 'mre': 0.5265267481933713,
 'peakR2': -0.4421834625322998,
 'maxAggR2': -0.07834201388888884,
 'meanAggR2': -9.864738343253965,
 'minAggR2': -29.38888888888888}