In [1]:
import sys
import numpy as np
sys.path.append('D:/ewhalen/OneDrive - Massachusetts Institute of Technology/research/toolbox/caeSurrogateUtility')
import caeUtility as cu

In [2]:
trueFields = [np.array([0.1, 0.1, 0.3]), 
              np.array([0.1, 0.2, 0.5]),
              np.array([1.7, 0.2, 0.6])]

predictions = [np.array([0.0, 0.2, 0.2]), 
               np.array([0.0, 0.2, 0.9]),
               np.array([1.6, 0.1, 0.6])]

cu.computeFieldLossMetrics(trueFields, predictions, level='point')

{'errors': [array([ 0.1, -0.1,  0.1]),
  array([ 0.1,  0. , -0.4]),
  array([0.1, 0.1, 0. ])],
 'relErrs': [array([ 1.        , -1.        ,  0.33333333]),
  array([ 1. ,  0. , -0.8]),
  array([0.05882353, 0.5       , 0.        ])]}

In [3]:
cu.computeFieldLossMetrics(trueFields, predictions, level='field')

{'mse': [0.01, 0.05666666666666668, 0.006666666666666658],
 'mae': [0.09999999999999999, 0.16666666666666666, 0.06666666666666662],
 'maxAE': [0.1, 0.4, 0.1],
 'mae/peak': [0.3333333333333333, 0.3333333333333333, 0.03921568627450978],
 'maxAE/peak': [0.33333333333333337, 0.8, 0.05882352941176471],
 'relEAtPeak': [0.33333333333333326, 0.8, 0.05882352941176463]}

In [4]:
cu.computeFieldLossMetrics(trueFields, predictions, level='set')

{'mse': 0.024444444444444446,
 'mae': 0.1111111111111111,
 'peakR2': 0.8430232558139534,
 'meanAggR2': -1.2201450892857149}

In [5]:
cu.computeFieldLossMetrics(trueFields, predictions, level='point_agg')

{'mse': array([0.01      , 0.00666667, 0.05666667]),
 'mae': array([0.1       , 0.06666667, 0.16666667]),
 'r2': array([ 0.98242188, -2.        , -2.64285714])}

In [6]:
cu.baseline(trueFields, avgLevel='point', level='set')

{'mse': 0.19555555555555557,
 'mae': 0.2888888888888889,
 'peakR2': -0.10465116279069786,
 'meanAggR2': 0.0}

In [7]:
cu.baseline(trueFields, avgLevel='set', level='set')

{'mse': 0.2328395061728395,
 'mae': 0.34074074074074073,
 'peakR2': -0.4421834625322998,
 'meanAggR2': -9.864738343253965}